{{ config(tags= ['load']) }}

WITH  SOURCE  AS 
( SELECT 
ID,
FNAME,
MNAME,
LNAME,
XNAME,
DEGREE,
SEX,
DOB,
CUR_ROW_IND,
REC_PRCS_TYP_CD
 FROM 
     {{ source('rv_prj' , 'PP_PRAC')}}
)
SELECT 
 ID AS PRAC_ID
,ID AS BK_PRCTNR_ID
,'BKCC' AS BKCC_PRCTNR
,FNAME AS FNM
,MNAME AS MNM
,LNAME AS LNM
,XNAME AS XNM
,DEGREE AS DEGR
,SEX AS SEX
,DOB AS DOB
,CUR_ROW_IND AS CUR_ROW_IND
, 'CO_CD' as CO_CD 
, 'REC_SRC' as REC_SRC 
,CASE WHEN REC_PRCS_TYP_CD in ('D') THEN 'Y' ELSE 'N' END AS DEL_IND
FROM 
SOURCE	 

